version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env  # usa as variáveis do .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start:dev

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ruraldb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
